name: 'CrediDeb Environment'

services:
  credideb:
    build:
      context: .
      dockerfile: Dockerfile
    image: credideb:0.0.1  # Gera a imagem a partir do Dockerfile, caso nao exista.
    container_name: credideb
    hostname: api
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_DATABASE: crediDebDb
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 9010:9010
      - 8080:8080
    deploy:
      resources:
        limits:
          cpus: '3.2'
          memory: '1.2GB'
    networks:
      - networker

  db: # Banco de dados
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: crediDebDb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d crediDebDb"]
      start_period: 10s
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: '1.5GB'
    networks:
      - networker

networks:
  networker: {}