CREATE TABLE IF NOT EXISTS CONTA(
  ID UUID not null,
  NOME varchar(100) not null,
  AGENCIA int not null,
  NUMERO_CONTA int not null,
  DATA_CRIACAO TIMESTAMP not null,
  PRIMARY KEY (ID),
  CONSTRAINT UC_AGENCIA_CONTA UNIQUE (AGENCIA,NUMERO_CONTA)
);

CREATE TABLE IF NOT EXISTS TRANSACAO(
  ID UUID not null,
  ID_CONTA UUID not null,
  TIPO_TRANSACAO varchar(10) not null,
  VALOR DECIMAL(10,2) not null,
  DATA_CRIACAO TIMESTAMP,
  PRIMARY KEY (ID),
  FOREIGN KEY (ID_CONTA) REFERENCES CONTA(ID)
);