CREATE TABLE IF NOT EXISTS CONTA(
  ID BINARY(16) not null,
  NOME varchar(100) not null,
  AGENCIA int not null,
  NUMERO_CONTA int not null,
  DATA_CRIACAO DATETIME not null,
  PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS TRANSACAO(
  ID BINARY(16) not null,
  ID_CONTA BINARY(16) not null,
  TIPO_TRANSACAO varchar(10) not null,
  VALOR DECIMAL(10,2) not null,
  DATA_CRIACAO DATETIME,
  PRIMARY KEY (ID),
  FOREIGN KEY (ID_CONTA) REFERENCES CONTA(ID)
);

--INSERT INTO crediDebDb.CONTA
--(ID, NOME, AGENCIA, CONTA, DATA_CRIACAO)
--VALUES(2, 'Nome', '111', 111, NOW());
--
--
--INSERT INTO crediDebDb.TRANSACAO
--(ID, ID_CONTA, TIPO, VALOR, DATA_CRIACAO)
--VALUES(2, 2, 'CREDITO', 1.15, NOW());